# Generated by Django 3.0.8 on 2020-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200702_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/media/products_images/<django.db.models.query_utils.DeferredAttribute object at 0x7fc9a3f2ed90>'),
        ),
    ]
