# Generated by Django 3.0.8 on 2020-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200702_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to="f'static/media/products_images/{Product.uid}/'"),
        ),
    ]
