# Generated by Django 3.0.8 on 2020-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200702_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/media/products_images/<django.db.models.query_utils.DeferredAttribute object at 0x7f7dd66a5d90>/'),
        ),
    ]
