# Generated by Django 3.0.8 on 2020-07-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated',
        ),
    ]
